server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  gzip on;
  gzip_types application/json text/css application/javascript image/svg+xml;
  location / {
    try_files $uri $uri/ /index.html;
  }
}
